version: '3'

services:
  commercionetworknode0:
    container_name: commercionetworknode0
    image: "commercionetwork/commercionetworknode"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
    environment:
      - ID=0
      - LOG=${LOG:-commercionetwork.log}
      - BINARY=/app/build/commercionetworkd
    volumes:
      - ./build:/commercionetwork:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  commercionetworknode1:
    container_name: commercionetworknode1
    image: "commercionetwork/commercionetworknode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-commercionetwork.log}
      - BINARY=/app/build/commercionetworkd
      - TZ=Asia/Colombo
    volumes:
      - ./build:/commercionetwork:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  commercionetworknode2:
    container_name: commercionetworknode2
    image: "commercionetwork/commercionetworknode"
    environment:
      - ID=2
      - LOG=${LOG:-commercionetwork.log}
      - BINARY=/app/build/commercionetworkd
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/commercionetwork:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  commercionetworknode3:
    container_name: commercionetworknode3
    image: "commercionetwork/commercionetworknode"
    environment:
      - ID=3
      - LOG=${LOG:-commercionetwork.log}
      - BINARY=/app/build/commercionetworkd
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/commercionetwork:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5


  proxy-nginx:
    container_name:   proxy-nginx
    image: "nginx"
    ports:
      - "7123:7123"
      - "7124:7124"
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

