# Dockerfile References: https://docs.docker.com/engine/reference/builder/

FROM golang:latest  

WORKDIR /root/

ARG LOG_DIR=/root/logs
ARG CHAIN_DIR=/root/chain
ARG GENESIS_DIR=/root/genesis

# Create Log Directory
RUN mkdir -p ${LOG_DIR}
RUN mkdir -p ${CHAIN_DIR}
RUN mkdir -p ${GENESIS_DIR}

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/build/Linux-AMD64/cncli .
COPY --from=builder /app/build/Linux-AMD64/cnd .
COPY container_exec.sh .
RUN chmod +x container_exec.sh

# Declare volumes to mount
VOLUME [${LOG_DIR}]
VOLUME [${CHAIN_DIR}]
VOLUME [${GENESIS_DIR}]

# Command to run the executable
CMD ./container_exec.sh



